name: C++ CI with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 在 Linux 上设置 g++ 编译器
    - name: Install g++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        echo "CXX=g++" >> $GITHUB_ENV

    # 创建构建目录
    - name: Create Build Directory
      run: mkdir -p build

    # 运行 CMake 配置
    - name: Configure CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    # 构建项目
    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    # 如果有测试，可以添加测试步骤
    # - name: Test
    #   working-directory: ./build
    #   run: ctest -C Release

    # 可选：上传构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dp_study-ubuntu-gcc
        path: build/dp_study*
