name: C++ CI with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    # 使用输出参数将构建信息传递给后续作业
    outputs:
      version: ${{ steps.version.outputs.version }}
      commit_sha: ${{ github.sha }}
    # 在多个操作系统上运行
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # 多个编译器版本
        compiler: [g++, clang++, cl]
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
          - os: windows-latest
            compiler: cl
          - os: macos-latest
            compiler: clang++
      # 如果一个矩阵构建失败，其他构建继续
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    # 设置版本号（从0.0.1开始）
    - name: Set Version
      id: version
      # 使用bash shell确保兼容性
      shell: bash
      run: |
        # 设置错误处理以捕获任何命令失败
        set -e
        
        # 检查是否存在现有的release
        # 添加错误处理，允许命令失败
        EXISTING_TAGS=""
        if git ls-remote --tags origin > /dev/null 2>&1; then
          # 如果git ls-remote成功，尝试获取标签
          EXISTING_TAGS=$(git ls-remote --tags origin | grep -o 'refs/tags/v[0-9]\+\.[0-9]\+\.[0-9]\+')
          
          # 检查是否有标签，并使用兼容的排序方法
          if [ -n "$EXISTING_TAGS" ]; then
            # 使用更兼容的排序方法，确保跨平台一致性
            LATEST_TAG=$(echo "$EXISTING_TAGS" | sort -t. -k1,1n -k2,2n -k3,3n | tail -n 1 | sed 's/refs\/tags\/v//')
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            NEW_PATCH=$((PATCH + 1))
            echo "version=${MAJOR}.${MINOR}.${NEW_PATCH}" >> $GITHUB_OUTPUT
            echo "Using next version: v${MAJOR}.${MINOR}.${NEW_PATCH}"
            exit 0
          fi
        fi
        
        # 如果没有现有标签或命令失败，使用初始版本0.0.1
        echo "No existing tags found, using initial version 0.0.1"
        echo "version=0.0.1" >> $GITHUB_OUTPUT

    # 在 Linux 上设置编译器
    - name: Set compiler (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        if [ "${{ matrix.compiler }}" = "g++" ]; then
          sudo apt-get install -y g++
          echo "CXX=g++" >> $GITHUB_ENV
        else
          sudo apt-get install -y clang
          echo "CXX=clang++" >> $GITHUB_ENV
        fi

    # 在 macOS 上设置编译器
    - name: Set compiler (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "PATH=/usr/local/opt/llvm/bin:$PATH" >> $GITHUB_ENV

    # 创建构建目录
    - name: Create Build Directory
      run: mkdir -p build

    # 在 Linux/macOS 上运行 CMake 配置
    - name: Configure CMake (Linux/macOS)
      if: matrix.os != 'windows-latest'
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    # 在 Windows 上运行 CMake 配置
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    # 构建项目
    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    # 如果有测试，可以添加测试步骤
    # - name: Test
    #   working-directory: ./build
    #   run: ctest -C Release

    # 上传构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dp_study-${{ matrix.os }}-${{ matrix.compiler }}
        path: |
          build/dp_study*
          build/dp_study.exe
        # 保留1天的构建产物
        retention-days: 1

  # 创建和发布GitHub Release
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    # 显示下载的文件结构用于调试
    - name: List downloaded files
      run: ls -laR artifacts
    
    # 重命名文件，使其包含版本信息
    - name: Rename artifacts
      run: |
        mkdir -p release_assets
        VERSION=${{ needs.build.outputs.version }}
        
        # 遍历所有下载的产物
        for dir in artifacts/*; do
          PLATFORM=${dir#artifacts/}
          if [ -d "$dir" ]; then
            cd "$dir"
            # 查找可执行文件
            for file in dp_study*; do
              if [ -f "$file" ]; then
                # 处理Windows可执行文件
                if [[ "$file" == *.exe ]]; then
                  NEW_NAME="dp_study_${PLATFORM}_v${VERSION}.exe"
                else
                  # 处理Linux/macOS可执行文件
                  NEW_NAME="dp_study_${PLATFORM}_v${VERSION}"
                fi
                echo "Renaming $file to $NEW_NAME"
                mv "$file" ../../release_assets/$NEW_NAME
              fi
            done
            cd ../..
          fi
        done
    
    # 创建GitHub Release
    - name: Create GitHub Release
      id: create_release
      uses: actions/github-script@v7
      env:
        VERSION: ${{ needs.build.outputs.version }}
        COMMIT_SHA: ${{ needs.build.outputs.commit_sha }}
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const version = process.env.VERSION;
          const commitSha = process.env.COMMIT_SHA;
          const timestamp = process.env.TIMESTAMP;
          
          // 创建Release
          const release = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${version}`,
            name: `Release v${version}`,
            body: `## dp_study v${version}\n\n**更新内容：**\n- 自动从main分支构建的最新版本\n- 支持多平台（Windows, Linux, macOS）\n- 支持多编译器（GCC, Clang, MSVC）\n\n**构建信息：**\n- 提交哈希: ${commitSha}\n- 构建时间: ${timestamp}`,
            draft: false,
            prerelease: false
          });
          
          // 输出upload_url供后续步骤使用
          core.setOutput('upload_url', release.data.upload_url);
    
    # 上传所有构建产物到Release
    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_assets/*
        asset_name: '*'
        asset_content_type: application/octet-stream
